commons-lang-2.6.jar
jconn4.jar
jtds-1.3.1.jar
sqljdbc4.jar
activation.jar
com.springsource.javax.activation-1.1.0.jar
com.springsource.javax.jms-1.1.0.jar
com.springsource.org.dom4j-1.6.1.jar
commons-beanutils-1.7.0.jar
commons-collections-3.1.jar
commons-dbcp-1.4.jar
commons-lang-2.6.jar
commons-logging-1.1.1.jar
commons-pool-1.5.5.jar
EccpressoFIPS.jar
EccpressoFIPSJca.jar
ehcache-1.1.jar
ezmorph-1.0.3.jar
hibernate3.jar
jackson-jaxrs-1.9.6.jar
jconn4.jar
jsafe.jar
jsafeJCE.jar
json_simple-1.1.jar
json-lib-2.1-jdk15.jar
json-lib-2.4-jdk15.jar
jsr173_1.0_api.jar
jta.jar
log4j-1.2.15.jar
mail.jar
mybatis-3.4.5.jar
mybatis-spring-1.3.1.jar
org.springframework.asm-3.0.5.RELEASE.jar
org.springframework.beans-3.0.5.RELEASE.jar
org.springframework.context-3.0.5.RELEASE.jar
org.springframework.context.support-3.0.5.RELEASE.jar
org.springframework.core-3.0.5.RELEASE.jar
org.springframework.expression-3.0.5.RELEASE.jar
org.springframework.jdbc-3.0.5.RELEASE.jar
org.springframework.jms-3.0.5.RELEASE.jar
org.springframework.orm-3.0.5.RELEASE.jar
org.springframework.test-3.0.5.RELEASE.jar
org.springframework.transaction-3.0.5.RELEASE.jar
smjavaagentapi.jar
smjavasdk2.jar
tibjms.jar
tibrvjms.jar
velocity-1.4.jar
xmlsec.jar
xsdlib.jar
